= Kudu developer velocity
:toc:

== ⚠ Disclaimer ⚠
Kudu developer images, and VSCode integration is experimental, this is the initial revision.
If you encounter any issues, or have suggestions, feel free to raise a PR. Thank you!

== How to use it \ Example workflow
Prerequisites:

* make a Kudu fork
* install docker on your machine
* install vscode 
** install "Dev Containers" extension

Notions:

* VSCode command palette: CMD+SHFT+P
* GoTo file: CMD+P

Setup 

. Pull down the Kudu debug build image: docker pull murculus/debug
. Bare clone your fork: git clone --bare <your_fork> (-> $KUDU_ROOT)
. Clone this dev velocity repo (-> $KUDU_DEV_VELOCITY_ROOT)
. git config --global --add safe.directory $KUDU_ROOT
. cd $KUDU_ROOT
. git worktree add master master
. cd master
. cp -R $KUDU_DEV_VELOCITY_ROOT/vscode/.devcontainer $KUDU_ROOT/master
. cp -R $KUDU_DEV_VELOCITY_ROOT/vscode/.vscode $KUDU_ROOT/master
. code . (open vscode)
. Command palette: "Dev Containers: Open Folder in Container ... "
. Hit CMP+P, then type "task" and hit space and a list of pre-defined tasks are listed
.. Clean build folder
.. Debug,Release,Asan,Tsan build commands

The VSCode extension forwards your local SSH agent if one is running: https://code.visualstudio.com/docs/remote/containers#_using-a-credential-helper[link]. This is necessary if you want to push code from the dev container to your remote fork.

== Published images
All the published images can be found at: https://hub.docker.com/u/murculus

* murculus/dev
** ubuntu18.04 base image, prerequisite packages are installed through apt
** this is provided by all the bootstrap-*.sh scripts from https://github.com/apache/kudu/tree/master/docker
* murculus/thirdparty
** contains all the built, uninstrumented thirdparty packages
** provided by this script: https://github.com/apache/kudu/blob/master/thirdparty/build-if-necessary.sh
* murculus/debug *(default recommended image)*
** Kudu debug build type
* murculus/release
** Kudu release build type
* murculus/thirdparty_all
** contains all the built, uninstrumented and instrumented thirdparty packages
** provided by this script: https://github.com/apache/kudu/blob/master/thirdparty/build-if-necessary.sh with the 'all' switch
* murculus/asan
** Kudu address sanitizer build type
* murculus/tsan
** Kudu thread sanitizer build type

== How it works
=== Git worktrees

https://www.theserverside.com/blog/Coffee-Talk-Java-News-Stories-and-Opinions/Use-this-git-worktree-add-example-and-never-switch-branches-again[Intro to git worktrees.]
Usually we have a repository, which is cloned into a folder. If we switch branhces, the contents of this exact folder change.

----
Kudu 
|_.git/
|_.gitignore
|_<source_files@master>
----

With git worktrees you have a top level folder, without any of the actual source files, hence the --bare clone. Then each added branch gets a new subfolder. These subfolders are basically git repos, checked out at that given branch. Since each branch lives in a different folder, these can be opened in a parallel fashion. -> you get the ability to work on multiple branches at the same time!

----
Kudu
|_HEAD
|_refs
|
|_master/ 
|   |_.git/ (@master)
|   |_.gitignore (@master)
|   |_<source_files@master>
|
|_feature1/
    |_.git/ (@feature1)
    |_.gitignore (@feature1)
    |_<source_files@feature1>
----

=== Host/container mapping
The development images are pretty simple. Kudu is built under /kudu , and thats it.
Whenever you open a worktree folder in vscode, and click "Open Folder in Container", the host worktree folder gets mounted to /mnt/kudu.


----
------                       |          -----------
|Host|                       |          |Container|
------                       |          -----------
                             |
                             |          /kudu/ 
                             |
                             |          ▲    |  2.
                             |      1.  |    ▼
                             |
/<your_kudu>/feature1/  <--bind-->      /mnt/kudu/ <- the host 
                             |
                             |
----
1. On VSCode startup, your worktree folder is mounted into the container. The contents can be synced to /kudu. For example the .git folder to have branch and remote info setup. What gets synced on startup is controlled by the "postCreateCommand" in devcontainer.json.
2. On every save the contents of /kudu are rsynced to /mnt/kudu, to persist changes outside of the container. This is controlled by "runOnSave.commands" in settings.json.